# ===============================
# Custom properties
# ===============================

server.cofiguration.resources=work

# ===============================
# Web
# ===============================

server.port=8888
server.error.path=/Error
server.error.include-exception=true
server.error.include-stacktrace=always

# ===============================
# Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://db:5432/store
spring.datasource.username=app
spring.datasource.password=secr3t

# ===============================
# JPA
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.hibernate.ddl-auto=create

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:import.sql

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=trace

# ===============================
# Mail
# ===============================

server.cofiguration.mail-host=
server.cofiguration.mail-port=
server.cofiguration.mail-username=
server.cofiguration.mail-password=
server.cofiguration.mail-ssl-enable=
server.cofiguration.mail-from=

# ===============================
# Logging
# ===============================

debug=false
logging.level.es.storeapp=WARN
logging.level.org.springframework.web=ERROR
logging.level.org.thymeleaf=ERROR
logging.file=work/server.log

# ===============================
# Management
# ===============================

management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=true
